import React from "react";

const GameData = {
  items:{
    diluents: [
      {
        id: 0,
        name: "Vin",
        price: 50,
        sellPrice: 25,
        icon:"https://placehold.co/40x40",
      },
      {
        id: 1,
        name: "Eau",
        price: 50,
        sellPrice: 25,
        icon:"https://placehold.co/40x40",
      },
      {
        id:2,
        name: "Huile",
        price: 50,
        sellPrice: 25,
        icon:"https://placehold.co/40x40",
      },
    ],
    herbs: [
      {
        id: 0,
        name: "Pétale de rose",
        price: 50,
        sellPrice: 25,
        icon:"https://placehold.co/40x40",
        isTransform: false,
      },
      {
        id: 1,
        name: "Flacon vide",
        price: 50,
        sellPrice: 25,
        icon:"https://placehold.co/40x40",
        isTransform: false,
      },
      {
        id: 2,
        name: "Hibiscus",
        price: 50,
        sellPrice: 25,
        icon:"https://placehold.co/40x40",
        isTransform: false,
      },
      {
        id: 3,
        name: "Racine de mandragore",
        price: 50,
        sellPrice: 25,
        icon:"https://placehold.co/40x40",
        isTransform: false,
      },
      {
        id: 4,
        name: "Pissenlit",
        price: 50,
        sellPrice: 25,
        icon:"https://placehold.co/40x40",
        isTransform: false,
      },
      {
        id: 5,
        name: "Feuillereve",
        price: 50,
        sellPrice: 25,
        icon:"https://placehold.co/40x40",
        isTransform: false,
      },
      {
        id: 6,
        name: "Feuille de bellombre",
        price: 50,
        sellPrice: 25,
        icon:"https://placehold.co/40x40",
        isTransform: false,
      },
      {
        id: 7,
        name: "Essence de Noxsombre",
        price: 50,
        sellPrice: 25,
        icon:"https://placehold.co/40x40",
        isTransform: false,
      },
      {
        id: 8,
        name: "Dent de Lion",
        price: 50,
        sellPrice: 25,
        icon:"https://placehold.co/40x40",
        isTransform: false,
      },
      {
        id: 9,
        name: "Fleur ardente",
        price: 50,
        sellPrice: 25,
        icon:"https://placehold.co/40x40",
        isTransform: false,
      },
      {
        id: 10,
        name: "Essence de Jasmin",
        price: 50,
        sellPrice: 25,
        icon:"https://placehold.co/40x40",
        isTransform: false,
      },
    ],
    potions: [
      {
        id: 0,
        name: "Potion de Lune",
        sellPrice: 150,
        icon:"https://placehold.co/40x40",
      },
      {
        id: 1,
        name: "Potion de vie",
        sellPrice: 150,
        icon:"https://placehold.co/40x40",
      },
      {
        id: 2,
        name: "Potion de souffle mortel",
        sellPrice: 150,
        icon:"https://placehold.co/40x40",
      },
      {
        id: 3,
        name: "Potion du Hardi",
        sellPrice: 150,
        icon:"https://placehold.co/40x40",
      },
      {
        id: 4,
        name: "Elixir d'amour",
        sellPrice: 150,
        icon:"https://placehold.co/40x40",
      },
    ],
  },
};

export default GameData;