const QuestsObject = () => [
  {
    fournisseur: "Yirsa https://github.com/Yirzaraji/",
    sujet: "Game Potion Quest",
    chapters: [
      {
        id: 1,
        title: "Chapitre I",
        description: "Les Doléances du Royaume",
        quests: [
          {
            id: 0,
            title: "La Blessure du Roi",
            description: "Le roi Arthur a été blessé lors d'une bataille contre les Saxons. Sa bureau refuse de guérir malgré les efforts de Merlin. Désespéré, Arthur envoie un messager à votre boutique pour demander une potion de guérison. Le roi a besoin de cette potion pour se remettre sur pied et continuer à protéger Camelot. Préparez une potion puissante en utilisant des herbes rares et des écailles de dragon pour accélérer sa guérison.",
            providedItems: ["Nouvelle quete", 300, 150],
            requiredItems: ["Potion de soin"],
            questGiverImg: "/images/yoda.jpg",
            isActive: true,
          },
          {
            id: 1,
            title: "Le Cœur de la Belle Eloïse",
            description: "Le jeune paysan Tom est amoureux de la belle Eloïse, mais elle ne lui prête aucune attention. Timide et maladroit, Tom a désespérément besoin d'un filtre d'amour pour gagner son cœur. Il se tourne vers vous, l'alchimiste renommé, pour préparer une potion qui fera fondre le cœur de sa bien-aimée. Utilisez des pétales de rose enchantés et un soupçon de miel de fée pour concocter cet élixir.",
            providedItems: ["Pétale de rose"],
            requiredItems: ["Potion de soin"],
            questGiverImg: "/images/yoda.jpg",
            isActive: false,
          },
          {
            id: 2,
            title: "Le Tournoi de Camelot",
            description: "Un grand tournoi se prépare à Camelot, et le chevalier Lancelot veut être au sommet de sa forme pour affronter ses adversaires. Bien que déjà extrêmement fort, il désire une potion qui lui donnera un avantage supplémentaire. Préparez une potion de force à base de griffes de griffon et de racine de mandragore pour l'aider à triompher dans les épreuves.",
            providedItems: ["Pétale de rose"],
            requiredItems: ["Potion de soin"],
            questGiverImg: "/images/yoda.jpg",
            isActive: false,
          },
        ],
      },
      {
        id: 2,
        title: "Chapitre II",
        description: "L'Ombre et la Magie",
        quests: [
          {
            id: 0,
            title: "Le Poison Mystérieux",
            description: "La reine Guenièvre a été empoisonnée lors d'un banquet. Personne ne sait qui est derrière cet acte ignoble, mais le temps presse. Le roi Arthur vous demande de concocter un antidote puissant pour sauver sa reine. Vous devrez mélanger des ingrédients rares tels que le venin de serpent royal et des feuilles de mandragore purifiées.",
            providedItems: ["Pétale de rose"],
            requiredItems: ["Potion de soin"],
            questGiverImg: "/images/yoda.jpg",
            isActive: false,
          },
          {
            id: 1,
            title: "L'Enigme d'Avalon",
            description: "Merlin, l'enchanteur légendaire, a besoin de vos compétences. Il doit résoudre une énigme ancienne pour accéder à Avalon, mais son esprit est embrouillé. Il demande une potion de clarté pour aiguiser ses pensées. Préparez une potion à base de larmes de licorne et de poudre de cristal lunaire pour aider Merlin à retrouver toute sa lucidité.",
            providedItems: ["Pétale de rose"],
            requiredItems: ["Potion de soin"],
            questGiverImg: "/images/yoda.jpg",
            isActive: false,
          },
          {
            id: 2,
            title: "L'Espionnage à Camelot",
            description: "Morgane, demi-sœur d'Arthur et magicienne puissante, a besoin d'une potion d'invisibilité pour infiltrer Camelot sans être vue. Bien que ses intentions soient douteuses, elle offre une récompense généreuse pour vos services. Concoctez une potion utilisant des ombres de minuit et de l'essence de brume.",
            providedItems: ["Pétale de rose"],
            requiredItems: ["Potion de soin"],
            questGiverImg: "/images/yoda.jpg",
            isActive: false,
          },
        ],
      },
      {
        id: 3,
        title: "Chapitre III",
        description: "La Quête des Vertus",
        quests: [
          {
            id: 0,
            title: "La Quête du Graal",
            description: "Le chevalier Perceval est en quête du Saint Graal, mais il se sent indigne et doute de ses capacités. Il cherche un élixir de sagesse pour lui donner la perspicacité nécessaire pour réussir sa mission sacrée. Préparez un élixir avec des feuilles de laurier sacré et des gouttes d'eau de source pure.",
            providedItems: ["Pétale de rose"],
            requiredItems: ["Potion de soin"],
            questGiverImg: "/images/yoda.jpg",
            isActive: false,
          },
          {
            id: 1,
            title: "Le Défi du Dragon",
            description: "Le chevalier Gauvain doit affronter un dragon redoutable qui terrorise un village voisin. Bien qu'il soit déjà courageux, il désire une potion de bravoure pour renforcer son cœur et affronter le monstre sans peur. Utilisez des plumes de phénix et des cendres volcaniques pour préparer cette potion.",
            providedItems: ["Pétale de rose"],
            requiredItems: ["Potion de soin"],
            questGiverImg: "/images/yoda.jpg",
            isActive: false,
          },
          {
            id: 2,
            title: "Le Mystère des Runes",
            description: "Taliesin, le grand druide et barde, est aux prises avec un mystère entourant des runes anciennes. Pour déchiffrer les secrets cachés, il demande une potion de vérité. Préparez une potion à base de fleurs de vérité et de perles de sagesse pour aider Taliesin à révéler les secrets des runes.",
            providedItems: ["Pétale de rose"],
            requiredItems: ["Potion de soin"],
            questGiverImg: "/images/yoda.jpg",
            isActive: false,
          },
        ],
      },
      {
        id: 4,
        title: "Chapitre IV",
        description: "Destins Croisés",
        quests: [
          {
            id: 0,
            title: "L'Héritier des Terres du Nord",
            description: "Le chef de clan Bredon et sa femme désirent un enfant depuis des années, mais sans succès. Ils espèrent qu'une potion de fécondité pourrait les aider à concevoir un héritier pour leur clan. Utilisez des racines de vie et des baies d'éternité pour créer une potion qui réalisera leur rêve de famille.",
            providedItems: ["Pétale de rose"],
            requiredItems: ["Potion de soin"],
            questGiverImg: "/images/yoda.jpg",
            isActive: false,
          },
          {
            id: 1,
            title: "L'Élixir du Courage de Perceval",
            description: "Perceval, chevalier aussi brave qu’ingénu, s’est porté volontaire pour affronter un dragon. Problème : il s’évanouit dès qu’il voit une flamme. Il te commande un élixir du courage pour dompter sa peur. Il insiste : « Pas trop fort ! » — la dernière potion qu’il a essayée l’a fait charger une vache en hurlant “Graal !”. Il faudra un équilibre parfait entre vigueur et raison… une alchimie délicate !",
            providedItems: ["Pétale de rose"],
            requiredItems: ["Potion de soin"],
            questGiverImg: "/images/yoda.jpg",
            isActive: false,
          },
          {
            id: 2,
            title: "Merlin et le Contre-Sort",
            description: "Merlin, encore lui, a renversé une potion de métamorphose sur son hibou, qui parle désormais en vers et refuse de dormir. Il te demande un contre-élixir de stabilisation magique, mais sans en avertir Arthur, qui croit que le hibou est un démon. Ta réputation d’alchimiste pourrait bien en dépendre…",
            providedItems: ["Pétale de rose"],
            requiredItems: ["Potion de soin"],
            questGiverImg: "/images/yoda.jpg",
            isActive: false,
          },
        ],
      },
    ],
  },
];

export default QuestsObject;